CREATE TABLE comment (
    comment_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    text TEXT NOT NULL, 
    date_commented TIMESTAMP DEFAULT now() NOT NULL,  
    author_id INTEGER REFERENCES app_user(app_user_id) ON DELETE CASCADE NOT NULL
); 
